print:
  name: Print Image
  description: Print a custom image
  target:
    device:
      manufacturer: Niimbot
  fields:
    payload:
      name: Payload
      description: payload to draw
      required: true
      example: look into supported_types.md for examples
    width:
      name: width
      description: width of label
      required: true
      example: 240
    height:
      name: height
      description: height of label
      required: true
      example: 120