print:
  name: Print Image
  description: Print Niimbot Label image
  target:
    device:
      manufacturer: Niimbot
  fields:
    payload:
      name: Payload
      description: payload to draw
      required: true
      example: examples
    rotate:
      name: rotate
      description: 0, 90, 180, 270
      required: false
      example: 90
    width:
      name: width
      description: width of label
      required: false
      example: 400
    height:
      name: height
      description: height of label
      required: false
      example: 240